apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sdg-workflow-controller.fullname" . }}-s3-sync
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: s3-sync
    {{- include "sdg-workflow-controller.labels" . | nindent 4 }}
data:
  dags_uri: {{ printf "s3://%s/dags/" .Values.global.secrets.aws.s3Dag.bucket | quote }}
  python_dependencies_uri: {{ printf "s3://%s/deps/" .Values.global.secrets.aws.s3Dag.bucket | quote }}
  plugins_uri: {{ printf "s3://%s/plugins/" .Values.global.secrets.aws.s3Dag.bucket | quote }}
